import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import { Splide, SplideSlide } from '@splidejs/react-splide';


export default function Home({ post }) {
  return (
    <div className="headContainer">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Splide
        options={{
          rewind: true,
          gap: '1rem',
        }}
        aria-label="My Favorite Images"
      >
        <SplideSlide>
          <img src="https://m.media-amazon.com/images/I/91h4Ht60f7L._SL1500_.jpg" alt="Image 1`" />
        </SplideSlide>
        <SplideSlide>
          <img  src="https://amc-theatres-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,w_1600/v1555343844/amc-cdn/general/306b854d-de9d-4bae-8bb6-cbb7efa6e54f/Cap_US_web.jpg" alt="Image 2" />
        </SplideSlide>
      </Splide>

      <div className='card-detail' style={{ backgroundImage: `url(https://image.tmdb.org/t/p/w400${post.backdrop_path})` }}>
        <div className='card-child'>
          <img src={`https://image.tmdb.org/t/p/w400${post.poster_path}`} alt="" srcset=""/>
          <div>
            <h3>{post.original_title}</h3>
            <p>{post.overview}</p>
          </div>
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps({ params }) {
  console.log("---------------------------------");
  console.log(params.id);
  console.log("---------------------------------");

  const res = await fetch(`https://api.themoviedb.org/3/movie/${params.id}?api_key=b9bec279d64c2bae6eff69777f4a0902&language=en-US`)
  const post = await res.json()
  console.log(post);
  return { props: { post } }
}