import Head from 'next/head'
import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom';
import ReactPaginate from 'react-paginate';
import {PaginatedItems} from "../component/pagination";
import Search from '../component/Search';

export default function Home({data}) {
	return (
		<div className="headContainer">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<nav><Search item={data}/></nav>
			<div id='page'><PaginatedItems itemsPerPage={4}  items={data.items}/></div>
		</div>
	)
}
export async function getServerSideProps() {
  const res = await fetch(`https://api.themoviedb.org/3/list/1?api_key=b9bec279d64c2bae6eff69777f4a0902&language=en-US`);
  const data = await res.json()
  return { props: {data } }
}						